<?php $this->headStyle()->captureStart();?>
.module-body .row > div{padding-left:20px;}
.module-body .row .btn-group{margin-right:15px;}
.module-body .row > div:first-child{margin-bottom:20px;}
.module-body .row:first-child{margin-bottom:20px;}

<?php $this->headStyle()->captureEnd();?>
<div class="container-fluid module-head">
	<h3><i class="far fa-list-alt"></i> Categorias</h3>
</div>
<?php
#exibe mensagens do metodo addErrorMessage();
echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));

#exibe mensagens do metodo addSucessMessage();
echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>
<div class="module-body">
	<div class="row">
		<div class="col-sm-6 col-md-7">
			<?php if($this->permitido($this->url('categoria',['action'=>'del']))):?>
			<div class="btn-actions btn-group" role="group">
				<button name="acao" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp;&nbsp;Ação
					<span class="caret"></span>
					</button>
				<ul class="dropdown-menu">
					<li><a id="excluir" href="#">Excluir selecionados</a></li>		
				</ul>
			</div>
			<?php endif;?>
			<button <?php if(!$this->permitido($this->url('categoria',['action'=>'cadastrar']))):?>disabled="disabled"<?php endif;?> id="btn-new" type="button" class="btn btn-primary">Nova categoria</button>		
		</div>
		<div class="col-sm-6 col-md-5">
		</div>
	</div>
	<div class="row">
		<div class="col-sm-push-6 col-sm-6 col-md-push-7 col-md-5">
			<form method="get">
				<div class="input-group">
					<input class="form-control" placeholder="Pesquisar" value="<?=$this->busca;?>" type="text" name="busca" />
					<div class="input-group-btn">
						<button style="margin-left: 10px;" class="btn btn-default" type="submit">Ok</button>
						<button style="margin-left: 10px;" class="btn btn-default" type="reset">limpar</button>
					</div>
				</div>
			</form>
		</div>
		<div class="col-sm-pull-6 col-sm-6 col-md-pull-5 col-md-7">
			<div class="input-group">
				<div class="input-group-addon">Ordem</div>
				<select  style="max-width:200px;" class="form-control fa" name="ordem">
					<option <?php if($this->ordem==1):?>selected<?php endif;?> value="1">Nome - A-Z</option>
					<option <?php if($this->ordem==2):?>selected<?php endif;?> value="2">Nome - Z-A</option>
				</select>
			</div>
		</div>
	</div>
	<?php if($this->busca <>''):?>
		<p>Resultado da pesquisa por "<?=$this->busca;?>":</p>
	<?php endif;?>
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th width="60px;">#</th>
				<th title="Selecionar tudo" width="10px"><input name="selecionador" type="checkbox" /></th>
				<th>Nome</th>
				<th class="hidden-xs" width="80px" >Artigos</th>
			</tr>
		</thead>
		<tbody>
			<?php if($this->categorias->getCurrentItemCount()>0):foreach($this->categorias as $categoria):?>
			<tr>
				<td><?=$categoria->getId(); ?></td>
				<td><input type="checkbox" name="cat[]" value="<?= $categoria->getId(); ?>" /></td>
				<td><a href="<?= $this->url('categoria',['action'=>'detalhar','id'=>$categoria->getId()]); ?>"><?= $categoria->getDescricao(); ?></a></td>
				<td class="hidden-xs"><?= $categoria->getArtigos()->count(); ?></td>
			</tr>
			<?php endforeach;else:?>
			<tr class="empty">
				<td colspan="6">Nenhum artigo</td>
			</tr>
			<?php endif;?>
		</tbody>
		<tfoot>
			<tr>
				<td align="right" colspan="6">
					<?= $this->paginationControl($this->categorias,'Sliding','admin/categoria/paginator.phtml',['route'=>'categoria','busca'=>$this->busca, 'ordem'=>$this->ordem]); ?>	
				</td>
			</tr>
		</tfoot>
	</table>
</div>
<?php
$script = <<<JS
$().ready(function(){
    var ordem = "{$this->ordem}";
    var busca = "{$this->busca}";
    var page = "{$this->page}";
    
    var query = function(){
        var url = '?';
        if(ordem != ''){
           url += 'ordem='+ordem;
        }

        if(busca != ''){
            if(url.length > 1){
                url += '&';
            }
            url += 'busca='+busca;
        }

        if(page != ''){
            if(url.length > 1){
                url += '&';
            }
            url += 'page='+page;
        }
        
        document.location.href = "{$this->url('categoria')}"+url;  
    };

    if($('input[name^=cat]:checked').length == 0){
       $('button[name=acao]').attr('disabled',true);
    }

    $('.module-body button[type=submit]').click(function(event){
        event.preventDefault();
        busca = $('input[name=busca]').val();
        query();    
    });

    $('select[name=ordem]').change(function(){
        ordem = $(this).val();
        query();
    });

    $('.module-body button[type=reset]').click(function(){
        busca='';
        query();
    });

    $('#btn-new').click(function(){
        document.location.href="{$this->url('categoria',['action'=>'cadastrar'])}";
    });

    $('input[name^=cat]').click(function(){
        if($(this).is(':checked')){
            $('button[name=acao]').attr('disabled',false);
        }else{
            if($('input[name^=cat]:checked').length == 0){
                 $('button[name=acao]').attr('disabled',true);
            }
        }
    });

    $('input[name=selecionador]').click(function(){
        if($(this).is(':checked')){
            $('input[name^=cat]').prop('checked',true);
            $('button[name=acao]').attr('disabled',false);
        }else{
            $('input[name^=cat]').prop('checked',false);
            $('button[name=acao]').attr('disabled',true);
        }
    });

    $('#excluir').click(function(event){
        event.preventDefault();

        selected = $('input[name^=cat]:checked');

        var ids = '';
        for(var i=0; i < selected.length;i++){
           ids += $(selected[i]).val();
           if(i != (selected.length -1)){
              ids += ',';  
           } 
        }
        document.location.href="{$this->url('categoria',['action'=>'del'])}/"+ids;
    });
});
JS;
$this->inlineScript()->appendScript($script);
?>