<div class="container">
<h1>Usuários</h1>
<hr/>
<div class="module module-cadastro clearfix">
	<div class="module-head">
			<h3>Cadastrar novo usuario</h3>
	</div>
	<div class="module-body">
	<form autocomplete="off" method="post">
		<div class="form-group">
			<label>Nome</label>
			<input class="form-control" type="text" name="nome" />
		</div>
		<div class="form-group">
			<label>Email</label>
			<input class="form-control" type="email" name="email" />
		</div>
		<div class="form-group form-group-sm">
			<label>login</label>
			<input class="form-control" type="text" name="login" />
		</div>
		<div class="form-group form-group-sm">
			<label>Senha</label>
			<input class="form-control" type="password" name="senha" />
		</div>
		<hr/>
		<div class="form-group form-group-sm">
			<label>Função</label>
			<select class="form-control" name="funcao">
				<option></option>
				<?php foreach($this->funcoes as $funcao):?>
				<option value="<?=$funcao->getId(); ?>"><?=$funcao->getDescricao(); ?></option>
				<?php endforeach;?>
			</select>
		</div>
		<hr/>
		<button type="submit" class="btn btn-success pull-right">Cadastrar</button>
	</form>
	</div>
</div>
</div>