<div class="container-fluid module-head">
	<h3>Nova conta de usuário</h3>
</div>
<br />
<div class="module-body clearfix">
	<form autocomplete="off" method="post">
		<div class="form-group">
			<label>Nome</label>
			<input class="form-control" type="text" name="nome" />
		</div>
		<div class="form-group">
			<label>Email</label>
			<input class="form-control" type="email" name="email" />
		</div>
		<div class="form-group form-group-sm">
			<label>login</label>
			<input class="form-control" type="text" name="login" />
		</div>
		<div class="form-group form-group-sm">
			<label>Senha</label>
			<input class="form-control" type="password" name="senha" />
		</div>
		<hr/>
		<div class="form-group form-group-sm">
			<label>Função</label>
			<select class="form-control" name="funcao">
				<option></option>
				<?php foreach($this->funcoes as $funcao):?>
				<option value="<?=$funcao->getId(); ?>"><?=$funcao->getDescricao(); ?></option>
				<?php endforeach;?>
			</select>
		</div>
		<hr/>
		<div class="pull-right">
			<button name="cancelar" onclick="window.history.go(-1);" type="button" class="btn btn-danger">Cancelar</button>&nbsp;&nbsp;&nbsp;
			<button type="submit" class="btn btn-success">Cadastrar</button>
		</div>	
	</form>
</div>