<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Usuário</h3>
</div>
<div class="module-body">
	<div class="btn-actions btn-group pull-right" role="group">
		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp;&nbsp;Ação
			<span class="caret"></span>
		</button>
		<ul class="dropdown-menu">
			<li><a href="<?=$this->url('usuario',['action'=>'editar','id'=>$this->usuario->getId()]);?>">Alterar</a></li>
			<li><a href="<?=$this->url('usuario',['action'=>'desativar','id'=>$this->usuario->getId()]);?>">Desativar</a></li>
			<li><a href="<?=$this->url('usuario',['action'=>'del','id'=>$this->usuario->getId()]);?>">Excluir</a></li>
		</ul>
	</div>
	<div class="form-group">
		<label class="control-label">Nome</label>
		<p class="form-control-static"><?=$this->usuario->getNome();?></p>
	</div>
	<div class="form-group">
		<label class="control-label">Email</label>
		<p class="form-control-static"><?=$this->usuario->getEmail();?></p>
	</div>
	<div class="form-group">
		<label class="control-label">Login</label>
		<p class="form-control-static"><?=$this->usuario->getLogin();?></p>
	</div>
	<div class="form-group">
		<label class="control-label">Senha</label>
		<p class="form-control-static">********* &nbsp;&nbsp;&nbsp;<a href="<?= $this->url('usuario',['action'=>'editar', 'id'=> $this->usuario->getId()]); ?>">Alterar</a></p>
	</div>
	<div class="form-group">
		<label class="control-label">Perfil de acesso</label>
		<p class="form-control-static"><?=$this->usuario->getRole()->getDescricao();?></p>
	</div>
</div>
<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Permissões de acesso</h3>
</div>
<div class="module-body">
	<?php foreach($this->recursos as $recurso):?>
	<table class="table table-striped">
		<thead>
			<tr>
				<th colspan="3"><?= $recurso->getNome();?></th>
			</tr>
		</thead>
		<tbody>
			<?php $role = $this->usuario->getRole(); foreach($recurso->getPermissoes() as $permissao):?>
			<tr>
				<td width="30px;"><?php if($role->getPermissoes()->contains($permissao) || $role->isRoot()):?><img src="<?= $this->basePath().'/img/checked.png';?>" width="20px" /><?php else: ?><img src="<?= $this->basePath().'/img/del.png';?>" width="20px" /><?php endif?></td>
				<td width="150px" class="hidden-xs"><?= $permissao->getNome();?></td>
				<td><?= $permissao->getDescricao(); ?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	<?php endforeach;?>
	<br/>
	<button name="cancelar" onclick="window.history.go(-1);" type="button" class="btn btn-link">Voltar</button>
</div>
