<?php
	$this->headScript()->appendFile($this->basePath('/js/functions.js'));
?>
<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Editar conta de <?= $this->usuario->getNome();?> </h3>
</div>
<br />
<div class="module-body clearfix">
	<form autocomplete="off" method="post">
		<div class="form-group">
			<label>Nome</label>
			<input value="<?= $this->usuario->getNome();?>" class="form-control" type="text" name="nome" />
		</div>
		<div class="form-group">
			<label>Email</label>
			<input value="<?= $this->usuario->getEmail();?>" class="form-control" type="email" name="email" />
		</div>
		<div class="form-group form-group-sm">
			<label>Login</label>
			<input value="<?= $this->usuario->getLogin();?>" class="form-control" type="text" name="login" />
		</div>
		<div class="form-group">
			 <input name="alterarsenha" type="checkbox">
			 <label class="info">alterar senha?</label>
		</div>
		<div id="ctrl-senha" class="form-group form-group-sm hide">
			<label>Senha</label>
			<input disabled class="form-control" type="password" name="senha" />
		</div>	
		<hr/>
		<div class="form-group form-group-sm">
			<label>Perfil de acesso</label>
			<select class="form-control" name="funcao">
				<option></option>
				<?php foreach($this->funcoes as $funcao):?>
				<option <?php if($this->usuario->getRole()->getId()==$funcao->getId()): ?>selected="selected"<?php endif;?> value="<?=$funcao->getId(); ?>"><?=$funcao->getDescricao(); ?></option>
				<?php endforeach;?>
			</select>
		</div>
		<hr/>
		<div class="pull-right">
			<button name="cancelar" onclick="window.history.go(-1);" type="reset" class="btn btn-danger">Cancelar</button>&nbsp;&nbsp;&nbsp;
			<button type="submit" class="btn btn-success">Salvar</button>
		</div>
	</form>
</div>
<script>
$().ready(function(){
	$('input[name=alterarsenha]').click(function(){
		if($('input[name=alterarsenha').is(":checked")){
			$("#ctrl-senha").removeClass('hide');
			$("input[name=senha]").attr("disabled",false);
		}else{
			$("#ctrl-senha").addClass('hide');
			$("input[name=senha]").attr("disabled",true);
		}
	});

});
</script>
