<?php 
$this->headScript()->appendFile($this->basePath("js/datatables.min.js"));
$this->headScript()->appendFile($this->basePath("js/datatables.bootstrap.min.js"));
$this->headLink()->appendStylesheet($this->basePath('css/datatables.min.css'));
$this->headLink()->appendStylesheet($this->basePath('css/datatables.bootstrap.css'));
?>
<div class="container-fluid module-head">
	<h3>Contas de usuários</h3>
</div>
<br />
<div class="container-fluid">
	<button id="btn-new" type="button" class="btn btn-primary">Novo</button>
	<table id="Tusuarios" class="table table-striped table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Nome</th>
				<th>Login</th>
				<th>Função</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php if(empty($usuarios)):?>
				<tr class="empty">
					<td colspan="5">Nenhum registro</td>
				</tr>
			<?php else:foreach($usuarios as $usuario):?>
			<tr>
				<td><?=$usuario->getId();?></td>
				<td><?=$usuario->getNome();?></td>
				<td><?=$usuario->getlogin();?></td>
				<td><?=$usuario->getRole()->getDescricao();?></td>
				<td align="center" width="150px">
					<button value="<?=$usuario->getId();?>" name="detalhar" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/detail.png';?>" /></button>
					<button value="<?=$usuario->getId();?>" name="editar" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/edit.png';?>" /></button>
					<button value="<?=$usuario->getId();?>" name="del" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/trash.png';?>" /></button>
				</td>
			</tr>
			<?php endforeach;endif;?>
		</tbody>
	</table>
</div>
<script>
$().ready(function(){

	$("#btn-new").click(function(){
		document.location.href = "<?php echo $this->url("usuario",["action"=>"cadastrar"]);?>";
	});

	$("button[name=editar]").click(function(){
		document.location.href = "<?php echo $this->url('usuario',['action'=>'editar']);?>/id/" + $(this).attr("value");
	});

	$("button[name=detalhar]").click(function(){
		document.location.href = "<?php echo $this->url('usuario',['action'=>'detalhar']);?>/id/" + $(this).attr("value");
	});

	$("button[name=del]").click(function(){
		if(confirm("Deseja remover permanentemente este usuário?")){
			document.location.href = "<?php echo $this->url('usuario',['action'=>'del']);?>/id/" + $(this).attr("value");
		}
	});
	
});
</script>