<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Contas de usuários</h3>
</div>
<?php
#exibe mensagens do método addErrorMessage();
echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));

#exibe mensagens do método addSucessMessage();
echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>
<div style="margin-top:20px;" class="module-body container-fluid">
	<button <?php if(!$this->permitido($this->url('usuario',['action'=>'cadastrar']))):?>disabled="disabled"<?php endif;?> id="btn-new" type="button" class="btn btn-primary">Novo</button>
	<div class="row" style="margin:15px 0;">
		<div class="hidden-xs col-sm-6 col-md-7"></div>
		<div class="col-xs-12 col-sm-6 col-md-5">
			<form class="" method="get">
				<div class="input-group">
					<input class="form-control" placeholder="Pesquisar" value="<?=$this->busca?>" type="text" name="busca" />
					<div class="input-group-btn">
						<button style="margin-left: 10px;" class="btn btn-default" type="submit">Ok</button>
						<button style="margin-left: 10px;" class="btn btn-default" type="reset">limpar</button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<?php if($this->busca <>''):?>
		<p>Resultado da pesquisa por "<?=$this->busca;?>":</p>
	<?php endif;?>
	<table id="Tusuarios" class="table table-striped table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Nome</th>
				<th>Login</th>
				<th class="hidden-xs">Perfil</th>
			</tr>
		</thead>
		<tbody>
			<?php if($this->usuarios->getCurrentItemCount()==0):?>
				<tr class="empty">
					<td colspan="4">Nenhum registro</td>
				</tr>
			<?php else:foreach($this->usuarios as $usuario):?>
			<tr>
				<td width="50px"><?=$usuario->getId();?></td>
				<td><a href="<?= $this->url('usuario',['action'=>'detalhar','id'=>$usuario->getId()]);?>"><?=$usuario->getNome();?></a></td>
				<td width="100px"><a href="<?= $this->url('usuario',['action'=>'detalhar','id'=>$usuario->getId()]);?>"><?=$usuario->getlogin();?></a></td>
				<td width="160px" class="hidden-xs"><a href="<?= $this->url('usuario',['action'=>'detalhar','id'=>$usuario->getId()]);?>"><?=$usuario->getRole()->getDescricao();?></a></td>
			</tr>
			<?php endforeach;endif;?>
		</tbody>
		<tfoot>
			<tr>
				<td align="right" colspan="4"><?= $this->paginationControl($this->usuarios,'Sliding','admin/usuario/paginator.phtml',['route'=>'usuario','busca'=>$this->busca]); ?></td>
			</tr>
		</tfoot>
	</table>
</div>
<script>
$().ready(function(){

	$("#btn-new:not(disabled)").click(function(){
		document.location.href = "<?php echo $this->url("usuario",["action"=>"cadastrar"]);?>";
	});

	$('.module-body button[type=reset]').click(function(){
		document.location.href="<?= $this->url('usuario');?>";
	});
});
</script>