<?= $this->doctype() ?>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        
        <?= $this->headTitle('Painel de controle')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'));
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->appendFile($this->basePath('js/jquery-ui.min.js'));
        ?>
    </head>
    <body>
        <!-- INICIO TOP NAV BAR -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Painel de controle"/>&nbsp;Painel de Controle
                    </a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Menu supeior</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav pull-right">
                            <li><a href="#">Suporte </a></li>
                            <li class="nav-user dropdown">
                            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <img class="nav-avatar" src="<?= $this->basePath('/img/user.png'); ?>" />
                                	<b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?= $this->url('usuario',['action'=>'detalhar']) ?>">Minha conta</a></li>
                                    <li><a href="#">Editar conta</a></li>                            
                                    <li class="divider"></li>
                                    <li><a href="<?= $this->url('login',['action'=>'logout']) ?>">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                </div>
            </div>
        </nav>
        <!-- FIM TOP NAV BAR -->
        <!-- INICIO BODY -->
        <div class="container-fluid bg-grey">
            <div class="container wrapper">
                <div class="row">
                    <!-- INICIO WRAPPER MENU ESQUERDO -->
                    <div class="col-sm-3">
                        <!-- INICIO MENU WIDGET -->
                        <ul class="menu nav rounded nav-tabs nav-stacked">
                            <li><a href="<?=$this->url('home');?>"><i class="glyphicon glyphicon-home"></i>Home</a></li>
                            <li><a href="#"><i class="glyphicon glyphicon-envelope"></i>Mensagens</a></li>
                        </ul>
                        <!-- FIM MENU WIDGET -->
                        <!-- INICIO MENU WIDGET -->
                        <ul class="menu nav rounded nav-tabs nav-stacked">
                            <li class="dropdown">
                                <a data-toggle="collapse" href="#submenu-usr" aria-expanded="false">
                                    <i class="glyphicon glyphicon-menu-down pull-right"></i>
                                    <i class="glyphicon glyphicon-menu-up pull-right"></i>
                                    <i class="glyphicon glyphicon-user"></i>Usuários
                                </a>
                                <ul class="nav collapse" id="submenu-usr">
                                    <li><a href="<?= $this->url('usuario',['action'=>'detalhar']) ?>">Meu cadastro</a></li>
                                    <li><a href="<?= $this->url('usuario');?>">Contas de usuário</a></li>
                                    <li><a href="<?= $this->url('role');?>">Permissão de acesso</a></li>
                                </ul>
                            </li>
                            <li><a href="#"><i class="glyphicon glyphicon-cog"></i>Configurações</a></li>
                        </ul>
                        <!-- FIM MENU WIDGET -->

                    </div>
                    <!-- FIM WRAPPER MENU ESQUERDO -->

                    <!-- INICIO WRAPPER CONTEUDO -->
                    <div class="col-sm-9">
                        <div class="content container-fluid bg-white rounded no-padding">
                            <?= $this->content;?>
                        </div>
                    </div>
                    <!-- FIM WRAPPER CONTEUDO -->

                </div>
            </div>
        </div>
        <!-- FIM BODY -->
        <div class="container-fluid">
            <footer>
                <p>&copy; 2018 - <?= date('Y') ?> Edmin Painel de controle - Todos direitos reservados.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
