<?= $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8" />
        
        <?= $this->headTitle('Painel de controle')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->appendStylesheet('https://use.fontawesome.com/releases/v5.6.3/css/all.css');
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->appendFile($this->basePath('js/jquery-ui.min.js'));
        ?>
        <?= $this->headStyle();?>
 
    </head>
    <body>
        <!-- INICIO TOP NAV BAR -->
        <nav id="navbartop" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a href="<?= $this->url('home') ?>" class="navbar-brand">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Painel de controle"/>
						Painel de Controle &nbsp;&nbsp;
                    </a>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Menu superior</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <?php if(@$this->usuario()):?>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav pull-right">
                        <li><a href="#">Suporte </a></li>
                        <li class="nav-user dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img class="nav-avatar" src="<?= $this->basePath('/img/user.png'); ?>" />
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="<?= $this->url('usuario',['action'=>'detalhar']) ?>">Minha conta</a></li>
                                <li><a href="<?=$this->url('usuario',['action'=>'editar']) ?>">Editar conta</a></li>                            
                                <li class="divider"></li>
                                <li><a href="<?= $this->url('login',['action'=>'logout']) ?>">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            <?php endif;?>
            </div>
        </nav>
        <!-- FIM TOP NAV BAR -->
        
        <!-- INICIO BODY -->
        <div id="body" class="container-fluid">
            <!-- INICIO WRAPPER BODY -->
            <div class="container-fluid wrapper">
                <?php if($this->usuario()):?>
                <div class="row">
                    <!-- INICIO WRAPPER MENU ESQUERDO -->
                    <div class="col-sm-3">
                        <!-- INICIO MENU WIDGET MENU-->
                        <?php  echo $this->menu()
                        ->setItens([
                            ['id'=>'home',
                            'active'=>['home'],
                            'label'=> 'Home',
                            'icone'=>'glyphicon glyphicon-home',
                            'link' => $this->url('home')],

                            ['id'=>'msg',
                            'active'=>['msg'],
                            'label'=>'Mensagens',
                            'icone'=>'glyphicon glyphicon-envelope',
                            'count'=> $this->msg()->countNews(),
                            'countClass'=>'green',
                            'link'=>$this->url('msg'),
                            ]
                        ])
                        ->setRouteName($this->CURRENT_ROUTE_NAME)
                        ->render(); 
                        ?>
                        <!-- FIM MENU WIDGET -->
                        <!-- INICIO MENU WIDGET -->
                        <?php echo $this->menu()
                        ->setItens([
                            ['id'=>'conteudo',
                             'active'=>['artigo','categoria'],
                             'label'=>'Conteúdo',
                             'icone' =>'far fa-newspaper',
                              'submenu' => [
                                  ['id'=>'categoria',
                                    'label'=>'Categorias',
                                    'link'=>$this->url('categoria')
                                  ],
                                  ['id'=>'artigos',
                                   'label'=>'Artigos',
                                   'link'=>$this->url('artigo'),
                                  ]
                              ]
                            ],
                            ['id'=> 'usuario',
                            'active'=>['usuario','role'],
                            'label'=> 'Usuários',
                            'icone'=>'glyphicon glyphicon-user',
                            'submenu'=>[
                                ['id'=>'usr-det',
                                'label'=>'Meu cadastro',
                                'link'=>$this->url('usuario',['action'=>'detalhar'])],

                                ['id'=>'usr-list',
                                'label'=>'Contas de usuários',
                                'link'=>$this->url('usuario')],

                                ['id'=>'role',
                                'label'=>'Perfil de acesso',
                                'link'=>$this->url('role')]
                             ]
                            ],

                        ['id'=> 'config',
                        'active'=>['config'],
                        'label'=>'Configurações',
                        'link'=>$this->url('config'),
                        'icone'=>'glyphicon glyphicon-cog']

                ])
                        ->setRouteName($this->CURRENT_ROUTE_NAME)
                        ->render(); 
                        ?>
                        <!-- FIM MENU WIDGET -->

                    </div>
                    <!-- FIM WRAPPER MENU ESQUERDO -->

                    <!-- INICIO WRAPPER CONTEUDO -->
                    <div class="col-sm-9">
                        <div id="content" class="content container-fluid rounded">
                            <?= $this->content;?>
                        </div>
                    </div>
                    <!-- FIM WRAPPER CONTEUDO -->
                <?php else:?>
                    <?= $this->content;?>
                <?php endif;?>
                </div>    
            </div>
            <!-- FIM WRAPPER BODY -->
        </div>
        <!-- FIM BODY -->
        <div class="container">
            <footer>
                <p>&copy; 2018 - <?= date('Y') ?> Zend Painel de controle - Todos direitos reservados.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
