<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Cadastrar perfil de acesso</h3>
</div>
<form autocomplete="off" method="post">
<div class="module-body module-cadastro clearfix">
		<div class="form-group form-group-sm">
			<label>Nome</label>
			<input class="form-control" type="text" name="descricao" />
		</div>
</div>
<div class="module-head">
	<h3>Permissões de acesso</h3>
</div>
<div class="module-body clearfix"/>
		<br/>
		<div class="form-group form-group-sm">
			<input class="inline" type="checkbox" name="root" value="*" />
			<label class="inline">Tudo</label>
		</div>
		<hr/>
		<?php foreach($this->recursos as $recurso):?>
		<table class="table table-striped">
			<thead>
				<tr>
					<td colspan=3><?= $recurso->getNome();?></td>
				</tr>
			</thead>
			<tbody>
				<?php foreach($recurso->getPermissoes() as $permissao):?>
				<tr>
					<td width="30px"><input name="permissao[]" value="<?= $permissao->getId();?>" type="checkbox" /></td>
					<td width="150px" class="hidden-xs"><?= $permissao->getNome();?></td>
					<td><?= $permissao->getDescricao();?></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<br/>
		<?php endforeach;?>
		<div class="pull-right">
			<button name="cancelar" onclick="window.history.go(-1);" type="reset" class="btn btn-danger">Cancelar</button>&nbsp;&nbsp;&nbsp;
			<button type="submit" class="btn btn-success">Cadastrar</button>
		</div>
</div>
	</form>
</div>
</div>
<script>
	$().ready(function(){
		$('input[name=root]').click(function(){
			if($(this).is(':checked')){
				$('.table input[name="permissao[]"]').attr('checked',true).attr('disabled',true);
			}else{
				$('.table input[name="permissao[]"]').attr('checked',false).attr('disabled',false);
			}
		});
	});
</script>