<div class="container-fluid">
	<?php foreach($this->recursos as $recurso):?>
	<table class="table table-striped">
		<thead>
			<tr>
				<th colspan="3"><?= $recurso->getNome();?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($recurso->getPermissoes() as $permissao):?>
			<tr>
				<td><?php if($this->role->getPermissoes()->contains($permissao) || $this->role->isRoot()):?><img src="<?= $this->basePath().'/img/checked.png';?>" width="15px" /><?php else: ?><img src="<?= $this->basePath().'/img/del.png';?>" width="15px" /><?php endif?></td>
				<td><?= $permissao->getNome();?></td>
				<td><?= $permissao->getDescricao(); ?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	<?php endforeach;?>
</div>