<div class="container-fluid module-head">
	<h3> <span class="glyphicon glyphicon-list" aria-hidden="true"></span> Editar perfil de <?= $this->role->getDescricao();?></h3>
</div>
<form autocomplete="off" method="post">
	<div class="module-body module-cadastro clearfix">
		<div class="form-group form-group-sm">
			<label>Nome</label>
			<input class="form-control" type="text" name="descricao" value="<?= $role->getDescricao(); ?>" />
		</div>
		<br/>
	</div>
	<div class="module-head">
			<h3>Permissõees de acesso</h3>
		</div>
		<br/>
	<div class="module-body clearfix">
		<div class="form-group form-group-sm">
			<input <?php if($role->isRoot()):?>checked="checked"<?php endif;?> class="inline" type="checkbox" name="root" value="*" />
			<label class="inline">Tudo</label>
		</div>
		<hr/>
		<?php foreach($this->recursos as $recurso):?>
		<table class="table table-striped">
			<thead>
				<tr>
					<td colspan=3><?= $recurso->getNome();?></td>
				</tr>
			</thead>
			<tbody>
				<?php foreach($recurso->getPermissoes() as $permissao):?>
				<tr>
					<td width="30px"><input <?php if($role->isRoot()):?>disabled<?php endif;?> <?php if($role->getPermissoes()->contains($permissao) || $role->isRoot()):?>checked="checked"<?php endif;?> name="permissao[]" value="<?= $permissao->getId();?>" type="checkbox" /></td>
					<td width="150px" class="hidden-xs"><?= $permissao->getNome();?></td>
					<td><?= $permissao->getDescricao();?></td>
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
		<br/>
		<?php endforeach;?>
		<div class="pull-right">
			<button name="cancelar" onclick="window.history.go(-1);" type="reset" class="btn btn-danger">Cancelar</button>&nbsp;&nbsp;&nbsp;
			<button type="submit" class="btn btn-success">Salvar</button>
		</div>
	
	</div>
</form>
</div>
</div>
<script>
	$().ready(function(){
		$('input[name=root]').click(function(){
			if($(this).is(':checked')){
				$('.module-body .table input[name="permissao[]"]').attr('checked',true).attr('disabled',true);
			}else{
				$('.module-body .table input[name="permissao[]"]').attr('checked',false).attr('disabled',false);
			}
		});
	});
</script>