<?php 
$this->headScript()->appendFile($this->basePath('js/functions.js'));
?>
<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-import" aria-hidden="true"></span> Permissões de acesso</h3>
</div>
<div class="container-fluid module-body">
	<button id="btn-new" type="button" class="btn btn-primary">Novo</button>
	<table id="Tfuncao" class="table table-striped table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Função</th>
				<th width="150px"></th>
			</tr>
		</thead>
		<tbody>
			<?php if(empty($funcoes)):?>
				<tr class="empty">
					<td colspan="5">Nenhum registro</td>
				</tr>
			<?php else:foreach($funcoes as $funcao):?>
			<tr>
				<td><?=$funcao->getId();?></td>
				<td><?=$funcao->getDescricao();?></td>
				<td align="center">
					<button value="<?=$funcao->getId();?>" name="permissao-detalhar" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/detail.png';?>" /></button>
					<button value="<?=$funcao->getId();?>" name="editar" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/edit.png';?>" /></button>
					<button value="<?=$funcao->getId();?>" name="del" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/trash.png';?>" /></button>
				</td>
			</tr>
			<?php endforeach;endif;?>
		</tbody>
	</table>
</div>
<script>
$().ready(function(){

	$('button[name="permissao-detalhar"]').click(function(){
		urlDialog('<?= $this->url('role',['action'=>'detalhar']);?>'+'/id/'+$(this).val(),'Permissões para '+$(this).closest('tr').find('td:eq(1)').html());
	});

	$("#btn-new").click(function(){
		document.location.href = "<?php echo $this->url("role",["action"=>"cadastrar"]);?>";
	});

	$("button[name=editar]").click(function(){
		document.location.href = "<?php echo $this->url('role',['action'=>'editar']);?>/id/" + $(this).attr("value");
	});

	$("button[name=del]").click(function(){
		if(confirm("Deseja remover permanentemente esta função?")){
			document.location.href = "<?php echo $this->url('role',['action'=>'del']);?>/id/" + $(this).attr("value");
		}
	});
	
	
});
</script>