<?php 
$this->headScript()->appendFile($this->basePath('js/functions.js'));
?>
<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-list" aria-hidden="true"></span> Perfil de acesso</h3>
</div>
<div class="container-fluid module-body">
	<button id="btn-new" type="button" class="btn btn-primary">Novo</button>
	<table id="Tfuncao" class="table table-striped table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Perfil</th>
				<th width="50px"></th>
			</tr>
		</thead>
		<tbody>
			<?php if(empty($funcoes)):?>
				<tr class="empty">
					<td colspan="5">Nenhum registro</td>
				</tr>
			<?php else:foreach($funcoes as $funcao):?>
			<tr>
				<td><?=$funcao->getId();?></td>
				<td><?=$funcao->getDescricao();?></td>
				<td align="center">
					<button value="<?=$funcao->getId();?>" name="permissao-detalhar" class="btn-icon"><img class="icon" src="<?= $this->basepath().'/img/detail.png';?>" /></button>
				</td>
			</tr>
			<?php endforeach;endif;?>
		</tbody>
	</table>
</div>
<script>
$().ready(function(){

	$('button[name="permissao-detalhar"]').click(function(){
		document.location.href = "<?php echo $this->url("role",["action"=>"detalhar"]);?>/id/"+$(this).val();
	});

	$("#btn-new").click(function(){
		document.location.href = "<?php echo $this->url("role",["action"=>"cadastrar"]);?>";
	});	
	
});
</script>