<div class="module-head">
	<h3><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Mensagens</h3>
</div>
<div class="module-body">
	<div id="msg" class="row">
		<div id="msg-menu" class="col-sm-3">
			<ul class="nav nav-pills nav-stacked">
				<li <?php if($this->box==1):?>class="active"<?php endif;?>><a href="<?=$this->url('msg-inbox');?>">Caixa de entrada</a></li>
				<li <?php if($this->box==2):?>class="active"<?php endif;?>><a href="<?=$this->url('msg-enviadas');?>">Enviadas</a></li>
			</ul>
		</div>
		<div id="msg-caixa" class="col-sm-9">
			<div class="container-fluid">
				<div class="navbar navbar-default">
					<div class="navbar-brand pull-left">
						<h3><?= $this->box==1?'Caixa de entrada':'Enviadas';?></h3>
					</div>
					<form class="pull-right">
						<input placeholder="Pesquisar" type="text" name="busca" />
					</form>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>Assunto</th>
							<th class="hidden-xs" width="25%">Remetente</th>
							<th width="80px">Data</th>
						</tr>
					</thead>
					<tbody>
						<?php if(count($this->mensagens)>0):foreach($this->mensagens as $msg):?>
						<tr <?php if($this->box==1 & !$msg->isVisualizada()):?>class="new"<?php endif;?>>
							<td><a href="<?=$this->url('msg-read',['id'=>$msg->getId()]) ?>"><?=$msg->getAssunto();?></a></td>
							<td class="hidden-xs"><a href="<?=$this->url('msg-read',['id'=>$msg->getId()]) ?>"><?=substr($msg->getRemetente()->getNome(),0,20);?></a></td>
							<td><a href="<?=$this->url('msg-read',['id'=>$msg->getId()]) ?>"><?php 
							       $data = $msg->getDataenvio();
							       if($data->format('d/m/Y')== date('d/m/Y')){
							           echo $data->format('H:i');
							       }else{
							           echo $data->format('d/m/Y');
							       }
							     ?></a>
							</td>
						</tr>
						<?php endforeach;else: ?>
						<tr class="empty">
							<td colspan="3">Nenhuma mensagem</td>
						</tr>
						<?php endif;?>
					</tbody>
					<tfoot>
						<tr>
							<?php if($this->box==1){
							    $route = 'msg-inbox';
							}else{
							    $route = 'msg-enviadas';
							}		    
							 ?>
							<td colspan="3"><?= $this->paginationControl($mensagens,'Sliding','admin/mensagem/paginator', ['route' => $route]); ?>
							</td>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>
<script>
$().ready(function(){
	$('#msg-caixa tbody tr:not(.empty)').click(function(){
		document.location.href = $(this).find('td a').attr('href');
	});
});
</script>