<div class="module-head">
	<h3><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Mensagens</h3>
</div>
<?php
#exibe mensagens do método addErrorMessage();
echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));

#exibe mensagens do método addSucessMessage();
echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>
<div style="padding:15px 10px 15px 25px;" class="module-body">
	<div id="msg" class="row">
		<div id="msg-menu" style="padding-left:0;" class="col-sm-3">
			<button class="btn btn-info" name="nova">Nova</button>
			<ul class="nav nav-pills nav-stacked">
				<li <?php if($this->box==1):?>class="active"<?php endif;?>><a href="<?=$this->url('msg');?>">Caixa de entrada</a></li>
				<li <?php if($this->box==2):?>class="active"<?php endif;?>><a href="<?=$this->url('msg',['action'=>'enviadas']);?>">Enviadas</a></li>
			</ul>
		</div>
		<div id="msg-caixa" style="padding-left:0;" class="col-sm-9">
			<div class="container-fluid">
				<div class="navbar navbar-default">
					<div class="navbar-brand pull-left">
						<h3><?= $this->box==1?'Caixa de entrada':'Enviadas';?></h3>
					</div>
					<div class="pull-right">
						<input placeholder="Pesquisar" type="text" name="busca" />
					</div>
				</div>
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th><span class="glyphicon glyphicon-tag" aria-hidden="true"></span>&nbsp;Assunto</th>
							<th class="hidden-xs" width="25%"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Remetente</th>
							<th width="80px"><span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp;Data</th>
						</tr>
					</thead>
					<tbody>
						<?php if($this->mensagens->getCurrentItemCount()>0):foreach($this->mensagens as $msg):?>
						<tr <?php if($this->box==1 && !$msg->foiLida()): ?>class="new"<?php endif;?> >
							<td><a href="<?=$this->url('msg',['action'=>'read','id'=>$msg->getMensagem()->getId()]) ?>"><?=$msg->getMensagem()->getAssunto();?></a></td>
							<td class="hidden-xs"><a href="<?=$this->url('msg',['action'=>'read','id'=>$msg->getMensagem()->getId()]) ?>"><?=$this->resumeNome($msg->getMensagem()->getRemetente()->getNome());?></a></td>
							<td><a href="<?=$this->url('msg',['action'=>'read','id'=>$msg->getMensagem()->getId()]) ?>"><?php 
							       $data = $msg->getMensagem()->getDataenvio();
							       if($data->format('d/m/Y')== date('d/m/Y')){
							           echo $data->format('H:i');
							       }else{
							           echo $data->format('d/m/Y');
							       }
							     ?></a>
							</td>
						</tr>
						<?php endforeach;else: ?>
						<tr class="empty">
							<td colspan="3">Nenhuma mensagem</td>
						</tr>
						<?php endif;?>
					</tbody>
					<tfoot>
						<tr>
							<td colspan="3"><?= $this->paginationControl($mensagens,'Sliding','admin/mensagem/paginator.phtml',['route'=>'msg','action'=>'find','box'=>$this->box]); ?>
							</td>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>
<?php
$script = <<<JS



$().ready(function(){

	$('#msg-caixa tbody').on('click','tr:not(.empty)',function(){
		document.location.href = $(this).find('td a').attr('href');
	});

	$('button[name=nova]').click(function(){
		document.location.href='{$this->url('msg',['action'=>'write'])}';
	});

	var typingTimer;
	$('#msg-caixa input[name=busca]').keyup(function(){
		clearTimeout(typingTimer);
		var input = $('#msg-caixa input[name=busca]');

    	typingTimer = setTimeout(function(){

    		 $(input).addClass('loading');
    		var urlRequest = '{$this->url('msg',['action'=>'find'])}?box={$this->box}&query='+$(input).val();
    		$.getJSON(urlRequest,function(data){
				$(input).removeClass('loading');
				updateMsgBox(data,'{$this->url('msg')}','find',$('#msg-caixa .table'));
			}).fail(function(jqxhr, textStatus, error){
				$(input).removeClass('loading');
				var e = jQuery.Event( 'keyup', { which: $.ui.keyCode.ENTER } );
				$(input).trigger(e);
			});

    	}, 1000);			

	});

	$('#msg-caixa tfoot > tr > td').on('click','.pagination a',function(event){
		event.preventDefault();
		var link = $(this);

		var urlRequest = $(this).attr('href');

    	$.getJSON(urlRequest,function(data){
			updateMsgBox(data,'{$this->url('msg')}','find',$('#msg-caixa .table'));
		}).fail(function(jqxhr, textStatus, error){
			var e = jQuery.Event( 'click', { which: $.ui.keyCode.ENTER } );
			$(link).trigger(e);
		});
	});


});
JS;
$this->inlineScript()->appendScript($script);
$this->inlineScript()->prependFile($this->basePath('/js/functions.js'));
$this->inlineScript()->prependFile($this->basePath('/js/moment.min.js'));
?>