<?php 
$this->headLink()->prependStylesheet($this->basePath('/froala/css/froala_style.min.css'));
$this->headStyle()->captureStart();?>
#collapse.btn {margin:0 0 2px 0;padding:0;}
#collapse[aria-expanded=true]{display:none;}
#mais.in{display:inline}
<?php $this->headStyle()->captureEnd();?>
<div class="module-head">
	<h3><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Mensagens</h3>
</div>
<div class="module-body">
	<div id="msg-caixa">
		<div id="msg-head" class="navbar navbar-default rounded">
			<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
			<span class="pull-right"><?=$this->mensagem->getDataenvio()->format('d/m/Y H:s');?></span>
			<h4>Assunto:&nbsp;<span style="font-size:16px"><?= $this->mensagem->getAssunto();?></span></h4>
			<h6><b>De:</b>&nbsp;<a href="<?=$this->url('usuario',['action'=>'detalhar','id'=>$mensagem->getRemetente()->getId()]);?>"><?= $this->resumeNome($mensagem->getRemetente()->getNome());?></a></h6>
			<div class="row">
				<div class="col-xs-12 col-sm-9">
					<h6><b>Para:</b>&nbsp;
			<?php
			$destinatarios = $mensagem->getDestinatarioMensagem();
			
			if(sizeof($destinatarios) > 3):
				for($i=0;$i<3;$i++){
					$nome = $this->resumeNome($destinatarios[$i]->getDestinatario()->getNome());
					echo "<a href=\"{$this->url('usuario',['action'=>'detalhar','id'=>$destinatarios[$i]->getDestinatario()->getId()])}\">".$nome.($i<sizeof($destinatarios)-1?', ':'')."</a>";
				}
			?>
			<span id="mais" class="collapse">
			<?php
				for($i=3;$i<sizeof($destinatarios);$i++){
					$nome = $this->resumeNome($destinatarios[$i]->getDestinatario()->getNome());
					echo "<a href=\"{$this->url('usuario',['action'=>'detalhar','id'=>$destinatarios[$i]->getDestinatario()->getId()])}\">".$nome.($i<sizeof($destinatarios)-1?', ':'')."</a>";	
				}
			?>
			</span>
			<button id="collapse" class="btn btn-link" aria-expanded=false data-toggle="collapse" data-target="#mais">e outros...</button>
			<?php
			else:
				for($i=0;$i<sizeof($destinatarios);$i++){
					$nome = $this->resumeNome($destinatarios[$i]->getDestinatario()->getNome());
					echo "<a href=\"{$this->url('usuario',['action'=>'detalhar','id'=>$destinatarios[$i]->getDestinatario()->getId()])}\">".$nome.($i<sizeof($destinatarios)-1?', ':'')."</a>";	
				}
			endif;
			?>		
					</h6>
				</div>
				<div class="col-sm-3"></div>
			</div>
			<a href="<?=$this->url('msg',['action'=>'write']); ?>?resp=<?=$this->mensagem->getId();?>" class="pull-right"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>&nbsp;Responder</a>
		</div>
		<div id="msg-body" class="rounded">
			<?=$this->mensagem->getTexto();?>
		</div>
	</div>
</div>
<button style="margin-bottom:15px;margin-left:15px" name="voltar" onClick="history.go(-1)" class="btn btn-link">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	Voltar
</button>