<div class="module-head">
	<h3><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Mensagens</h3>
</div>
<div class="module-body">
	<div id="msg-caixa">
		<div id="msg-head" class="navbar navbar-default rounded">
			<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
			<span class="pull-right"><?=$this->mensagem->getDataenvio()->format('d/m//Y H:s');?></span>
			<h4>Assunto:&nbsp;<span style="font-size:16px"><?= $this->mensagem->getAssunto();?></span></h4>
			<h6><b>De:</b> <?= $mensagem->getRemetente()->getNome();?></h6>
			<a href="<?=$this->url('msg',['action'=>'write']); ?>?resp=<?=$this->mensagem->getId();?>" class="pull-right"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>&nbsp;Responder</a>
			<?php
			foreach($mensagem->getDestinatarios() as $destinatario ):
				$nome = explode(' ',$destinatario->getNome());
				$nome = sizeof($nome) > 2? array_shift($nome).' '.array_pop($nome):$destinatario->getNome();
			endforeach;
			?>		

		</div>
		<div id="msg-body" class="rounded">
			<?=$this->mensagem->getTexto();?>
		</div>
	</div>
</div>
<button style="margin-bottom:15px;margin-left:15px" name="voltar" onClick="history.go(-1)" class="btn btn-link">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	Voltar
</button>