<?php 
$this->headLink()->appendStylesheet($this->basePath('/css/simple-editor.css'));
$this->headScript()->appendFile($this->basePath('/js/simple-editor.js'));
?>
<div class="module-head">
	<h3><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Enviar mensagem</h3>
</div>
<div class="module-body">
	<form method="post">
		<button type="reset" style="margin:15px;" name="voltar" onClick="history.go(-1)" class="btn btn-default">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			Voltar
		</button>
		<button type="submit" style="margin:15px;" name="submit" class="btn btn-submit pull-right">
			<span class="glyphicon glyphicon-" aria-hidden="true"></span>
			Enviar
		</button>
	<div id="msg-caixa">
		<div id="msg-head" class="navbar navbar-default rounded">
			<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
			<div class="input-group">
				<span class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Para:</span>
				<input type="text" name="destinatarios" class="form-control" />
			</div>
			<div class="input-group">
				<span class="input-group-addon">Assunto:</span>
				<input type="text" name="assunto" class="form-control" />
			</div>
		</div>
		<div id="msg-body" class="rounded">
			<textarea rows="10" name="texto" class="form-control"></textarea>
		</div>
	</div>
	</form>
</div>
