<div class="container container-login">
<?php if(!empty($this->erro)):?><div class="alert alert-danger" role="alert"><?php echo $this->erro; ?></div><?php endif;?>
<div class="container module module-login">
	<form method="POST" class="form-vertical">
		<div class="module-head">
			<h3>Entrar</h3>
		</div>
		<div class="module-body">
			<div class="control-group">
					<input class="span12" type="text" name="usuario" placeholder="Usuario">
			</div>
			<div class="control-group">
					<input class="span12" type="password" name="senha" placeholder="Senha">
			</div>
		</div>
		<div class="module-foot clearfix">
			<button type="submit" class="btn btn-primary pull-right">Login</button>
		</div>
	</form>
</div>
</div>