<?php $this->headLink()->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css');
?>
<div class="module module-login rounded col-xs-offset-2 col-xs-8 col-sm-offset-4 col-sm-4">
	<div class="module-head">
		<h3><i class="fa fa-lock" aria-hidden="true"></i>&nbsp;&nbsp;Autenticação</h3>
	</div>
	<form method="POST" autocomplete="false">
	<div class="module-body">
		<div class="form-group form-group-sm">
			<label>Login</label>
			<input name="usuario" class="form-control" type="text" />
		</div>
		<div class="form-group form-group-sm">
			<label>Senha</label>
			<input name="senha" class="form-control" type="password" />
		</div>
	</div>
	<div class="module-footer clearfix">
		<button class="btn btn-success pull-right">Entrar</button>
	</div>
	</form>
</div>