<?php
$this->headStyle()->captureStart();
?>
.alert{
	margin:50px 20px;
}
<?php
$this->headStyle()->captureEnd();
?>
<div class="container-fluid module-head">
	<h3><i class="fas fa-lock"></i> Acesso Negado</h3>
</div>
<div class="alert alert-warning">Desculpe, você não tem autorização para acessar esta página.</div>
<button style="margin-bottom:15px;margin-left:15px" name="voltar" onClick="history.go(-1)" class="btn btn-link">
	<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	Voltar
</button>