<?php
$this->headLink()->appendStylesheet($this->basePath('/css/jquery.datetimepicker.min.css'));
$this->headLink()->appendStylesheet($this->basePath('/css/bootstrap-select.min.css'));
$this->headLink()->appendStylesheet($this->basePath('/css/jquery-ui.min.css'));
$this->headLink()->appendStylesheet($this->basePath('/froala/css/froala_editor.pkgd.min.css'));
$this->headLink()->appendStylesheet($this->basePath('/froala/css/froala_style.min.css'));

$this->inlineScript()->appendFile($this->basePath('/js/jquery.datetimepicker.full.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/functions.js'));
$this->inlineScript()->appendFile($this->basePath('/js/moment.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/bootstrap-select.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/jquery-ui.min.js'));
$this->inlineScript()->appendFile($this->basePath('/froala/js/froala_editor.pkgd.min.js'));
$this->inlineScript()->appendFile($this->basePath('/froala/js/languages/pt_br.js'));

$this->headStyle()->captureStart();?>
.module-body .row > div{padding-left:20px;}
.module-body .row .btn-group{margin-right:15px;}
.module-body .row > div:first-child{margin-bottom:20px;}
.module-body .row:first-child{margin-bottom:20px;}
.module-body .nav li.active a{background: #efefef;font-weight:bold;}
.module-body .tab{display:none;}
.module-body .tab.visible{display:block;}
.module-body input{background-color:#fff !important;}
<?php $this->headStyle()->captureEnd();?>
<div class="container-fluid module-head">
	<h3><i class="far fa-newspaper"></i> Novo artigo</h3>
</div>
<?php
#exibe mensagens do metodo addErrorMessage();
echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));

#exibe mensagens do metodo addSucessMessage();
echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>
<div class="module-body clearfix">
	<ul	class="nav nav-tabs">
		<li class="active"><a href="#conteudo">Conteúdo</a></li>
		<li><a href="#publicacao">Publicação</a></li>
	</ul>
	<br/>
	<form method="post">
		<div id="conteudo" class="tab visible">
			<div class="form-group">
    			<div style="min-width:200px; max-width: 300px" class="input-group">
    				<label>Categoria</label>
    				<select data-live-search="true" class="form-control selectpicker" name="categoria">
    					<option></option>
    					<?php foreach($this->categorias as $categoria): ?>
    					<option value="<?= $categoria->getId(); ?>"><?= $categoria->getDescricao();?></option>
    					<?php endforeach;?>
    				</select>
    			</div>
			</div>
			<div class="form-group">
				<label>Titulo</label>
				<input maxlength="250" autocomplete="off" type="text" name="titulo" class="form-control" />
			</div>
			<div class="form-group">
				<label>Sub-titulo</label>
				<input maxlength="250" autocomplete="off" type="text" name="subtitulo" class="form-control" />
			</div>
			<div class="form-group">
				<label>Conteúdo</label>
				<textarea class="form-control" name="conteudo"></textarea>
			</div>
		</div>
		<div id="publicacao" class="tab">
			<div class="row">
				<div class="col-sm-4">
					<label>Autor</label>
					<div class="input-group">
						<div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
						<input type="hidden" value="<?= $this->autor->getId();?>" name="idautor" />
						<input readonly value="<?= $this->resumeNome($this->autor->getNome()); ?>" class="form-control" name="autor" />
					</div>
				</div>
				<div class="col-sm-4 col-sm-offset-1">
					<label>Data de publicação</label>
					<div class="input-group">
						<div class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></div>
						<input readonly value="<?= $this->data()->getDateTime(); ?>" class="form-control" name="datapublicacao" />
					</div>
				</div>
			</div>
		</div>
		<br/>
		<div class="pull-right">
			<button name="cancelar" onclick="window.history.go(-1);" type="reset" class="btn btn-danger">Cancelar</button>&nbsp;&nbsp;&nbsp;
			<button type="submit" class="btn btn-success">Salvar</button>
		</div>
	</form>
</div>
<?php 
$script = <<<JS
$().ready(function(){
    $.FroalaEditor.ICON_DEFAULT_TEMPLATE = 'font_awesome_5';
    $('textarea[name=conteudo]').froalaEditor({language:'pt_br',
                                                heightMin:200, 
                                                toolbarButtons: ['bold', 'italic', 'underline','align','insertLink','insertImage','insertVideo','insertFile','insertHR','undo', 'redo','html'],                                                
                                                imageUploadParam: 'imagem',
                                                imageUploadURL: "{$this->url('upload',['action'=>'imagem'])}",
                                                imageMaxSize: 5 * 1024 * 1024,
                                                imageAllowedTypes: ['jpeg', 'jpg', 'png'],
                                                fileUploadParam: 'arquivo',
                                                fileUploadURL: "{$this->url('upload',['action'=>'arquivo'])}",
                                                fileUploadMethod: 'POST',
                                                fileMaxSize: 5 * 1024 * 1024,
                                                fileAllowedTypes: ['*']
                                             })
                                              .on('froalaEditor.image.removed', function (e, editor, img) {
                                                  $.ajax({
                                                       method: "POST",
                                                       url: "{$this->url('upload',['action'=>'delimagem'])}",
                                                       data: {
                                                           imagem: $(img).attr('src')
                                                        }
                                                   });
                                               });

    $('.module-body .nav li').on('click', 'a', function(event){
        event.preventDefault();
        $('.module-body .nav li.active').removeClass('active');
        $(this).closest('li').addClass('active');
        id = $(this).attr('href');
        $('.module-body .tab').removeClass('visible');
        $('.module-body .tab'+id).addClass('visible');
    }); 

    $('.module-body input[name=autor]').click(function(){
        $('#content').append('<div id="dialog"></div>');
        $('#dialog').load("{$this->url('artigo',['action'=>'listausuarios'])}").dialog({width: "auto",
                                                                                    	position:{my:"center top", at:"center top+80", of: window},
                                                                                   		title: 'Selecionar autor',
                                                                               			width: dialogWidth,
                                                                               			maxHeight: dialogHeight,
                                                                               			modal: true,
                                                                               			close: false,
                                                                               			resizable: true,
                                                                                        close: function(){ $('#dialog').remove(); },
                                                                                        buttons: {
                                                                                          Cancelar: function(){
                                                                                             $(this).dialog('close');
                                                                                          },
                                                                                          Selecionar: function(){
                                                                                             var row = $('#dialog .table tbody tr.selected');
                                                                                             if($(row).find('input[name="idusuario"]').val() == null){
                                                                                               return alert('Selecione um autor!');
                                                                                             }

                                                                                             $('.module-body form input[name="idautor"]').val($(row).find('input[name="idusuario"]').val());
                                                                                             var nome = $(row).find('td:eq(1)').html();
                                                                                             if(nome.split(' ').length > 1){
                                                                                                nome = nome.split(' ').shift()+' '+nome.split(' ').pop();
                                                                                             }
                                                                                             $('.module-body form input[name="autor"]').val(nome);
                                                                                             $(this).dialog('close');
                                                                                          }
                                                                                        } 
                                                                                 });
    });

    jQuery.datetimepicker.setLocale('pt-BR');
    $('.module-body input[name=datapublicacao]').datetimepicker({format:'d/m/Y H:i', minDate:"{$this->data()->getDateTime()}"});
});
JS;
$this->inlineScript()->appendScript($script);
?>