<div class="container-fluid module-head">
	<h3><i class="far fa-newspaper"></i> Artigo</h3>
</div>
<div class="module-body">
	<div class="alert alert-danger" role="alert"><b>Atenção!</b> Você esta prestes a excluir os seguintes registros:</div>
	<table class="table table-striped">
		<thead>
			<tr>
				<th width="100">#</th>
				<th>Titulo</th>
				<th width="100" class="hidden-xs">Autor</th>
				<th width="100" class="hidden-xs">Acessos</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->artigos as $artigo):?>
			<tr>
				<td><?= $artigo->getId(); ?></td>
				<td><?= $artigo->getTitulo(); ?></td>
				<td class="hidden-xs"><?= $artigo->getAutor()->getNome(); ?></td>
				<td><?= $artigo->getAcessos(); ?></td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	<hr/>
	<h4>Segurança</h4>
	<div class="row">
		<div style="min-width:200px;" class="col-xs-3">
			<p><img class="captcha" src="<?=$this->basePath('/temp/captcha/'.$this->captcha.'.png');?>" /></p>
		</div>
		<div class="col-xs-9">
			<form method="POST" class="form-inline">
				<input type="hidden" name="captcha[id]" value="<?=$this->captcha;?>" />
				<div class="form-group">
					<input style="max-width: 200px;" type="text" class="form-control" name="captcha[input]" />
				</div>
				<button type="submit" class="btn btn-primary">Confirmar</button>
			</form>
			<p>Reescreva o codigo ao lado para confirmar a exclusão</p>
		</div>
	</div>
	<br/><br/><br/>
	<button type="button" class="btn btn-link" onClick="history.go(-1)">Voltar</button>
</div>