<?php 
$params=[];
if($this->action<>null){$params['action'] = $this->action;}
if($this->id<>null){$params['id'] = $this->id;}

$query = [];
if($this->busca <>null){$query['busca']=$this->busca;}
if($this->ordem <>null){$query['ordem']=$this->ordem;}
if($this->categoria <>null){$query['cat']=$this->categoria;}

if ($this->pageCount): ?>
<nav>
<ul class="pagination">

<!-- Previous page link -->
<?php if (isset($this->previous)): $q = ['query'=>['page'=>$this->previous]]; ?>
    <li>
      <a href="<?= $this->url($this->route,$params, $q); ?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>  
<?php else: ?>
    <li>
        <span aria-hidden="true">&laquo;</span>      
    </li>  
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li>
        <a href="<?= $this->url($this->route,$params, ['query'=>['page'=>$page]+$query]); ?>"><?= $this->escapeHtml($page); ?></a>
    </li>    
  <?php else: ?>
    <li>
        <span aria-hidden="true"><b><?= $this->escapeHtml($page); ?></b></span> 
    </li>    
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <li>

      <a href="<?php echo $this->url($this->route,$params, ['query'=>['page'=>$this->next]+$query]); ?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>  
<?php else: ?>
    <li>
        <span aria-hidden="true">&raquo;</span>      
    </li> 
<?php endif; ?>
</ul>
</nav>
<?php endif; ?>