<div class="container-fluid module-head">
	<h3><span class="glyphicon glyphicon-tasks" aria-hidden="true"></span> Dashboard</h3>
</div>
<?php
#exibe mensagens do método addErrorMessage();
echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));

#exibe mensagens do método addSucessMessage();
echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>